# Generated by Django 5.1.7 on 2025-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menuitem_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
